{
 "title": "WeaveNet (Cluster)",
 "description": "WeaveNet metrics at the cluster level.  It was made on top of the weave-net prometheus metrics. Please check this for more details https://www.weave.works/docs/net/latest/tasks/manage/metrics",
 "tags": [ "practo-managed" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   },
   { "name": "interval", "query": "4h" }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fast DP flows",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(weave_flows)" }
   ]
  },
  {
   "title": "Fast DP off",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(weave_flows == bool 0)" }
   ]
  },
  {
   "title": "IPAM Pending Allocates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_ipam_pending_allocates)"
    }
   ]
  },
  {
   "title": "IPAM Pending Claims",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(weave_ipam_pending_claims)" }
   ]
  },
  {
   "title": "Terminations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "cpm",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(weave_connection_terminations_total[1m]))"
    }
   ]
  },
  {
   "title": "Weave Pods",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(central_nodeagent:node_route_unhealthy_count)"
    }
   ]
  },
  {
   "title": "P2P Established",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"established\"})"
    }
   ]
  },
  {
   "title": "P2P Connecting",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"connecting\"})"
    }
   ]
  },
  {
   "title": "P2P Pending",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"pending\"})"
    }
   ]
  },
  {
   "title": "P2P Failed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"failed\"})"
    }
   ]
  },
  {
   "title": "P2P Retrying",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "format": "short",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"retrying\"})"
    }
   ]
  },
  { "title": "IPAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "IPAM Unreachable Percentage",
   "type": "graph",
   "description": "Percentage of all IP addresses owned by unreachable peers.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_ipam_unreachable_percentage, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPAM Unreachable Count",
   "type": "graph",
   "description": "Number of unreachable peers that own IPAM addresses.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_ipam_unreachable_count, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "IPAM Pending",
   "type": "graph",
   "description": " Number of pending claims.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_ipam_pending_allocates)",
     "legendFormat": "pending allocates"
    },
    { "expr": "sum(weave_ipam_pending_claims)", "legendFormat": "pending claims" }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Fast DP Flows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(weave_flows, \"node\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Rate of Terminated Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(rate(weave_connection_terminations_total[5m]), \"node\", \"$1\", \"instance\", \"(.*):.*\") > 0",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "P2P / Established",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"established\"})",
     "legendFormat": "connections established"
    }
   ]
  },
  {
   "title": "P2P / Connecting",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"connecting\"})",
     "legendFormat": "connections connecting"
    }
   ]
  },
  {
   "title": "P2P / Pending",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"pending\"})",
     "legendFormat": "pending connections"
    }
   ]
  },
  {
   "title": "P2P / Retrying",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"retrying\"})",
     "legendFormat": "retrying connections"
    }
   ]
  },
  {
   "title": "P2P / Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(weave_connections{state=\"failed\"})",
     "legendFormat": "failed connections"
    }
   ]
  },
  {
   "title": "P2P / Established",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sort(label_replace(weave_connections{state=\"established\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "P2P / Connecting",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 35 },
   "targets": [
    {
     "expr": "sort(label_replace(weave_connections{state=\"connecting\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "P2P / Pending",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sort(label_replace(weave_connections{state=\"pending\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "P2P / Failed",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 35 },
   "targets": [
    {
     "expr": "sort(label_replace(weave_connections{state=\"failed\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "P2P / Retrying",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_connections{state=\"retrying\"}, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Fast DP Flows (Current)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "sort_desc(label_replace(weave_flows, \"node_ip\", \"$1\", \"instance\", \"(.*):.*\"))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Pods Per Node (Current)",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "sort_desc(floor(label_replace(max by(node) (max by(instance) (kubelet_running_pod_count{job=\"kubelet\",metrics_path=\"/metrics\"}) * on(instance) group_left(node) kubelet_node_name{job=\"kubelet\",metrics_path=\"/metrics\"}) / max by(node) (kube_node_status_capacity{resource=\"pods\",unit=\"integer\",job=\"kube-state-metrics\"}) , \"node_ip\", \"$1.$2.$3.$4\", \"node\", \"^ip-([0-9]+)-([0-9]+)-([0-9]+)-([0-9]+).*$\") * 100))",
     "legendFormat": "{{node_ip}}"
    }
   ]
  },
  {
   "title": "Peer To Peer Connections Terminated",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 45 },
   "targets": [
    {
     "expr": "sort(label_replace(increase(weave_connection_terminations_total[1m]), \"node_ip\", \"$1\", \"instance\", \"(.*):.*\")) != 0",
     "legendFormat": "{{node_ip}}"
    }
   ]
  }
 ]
}